### ISSUE TITLE
AKAI/KMAI: Profanity checks for the bot

### ISSUE THREAD

**Issue by MaunicaKolla815** [BharatSahAIyak/kisai-bot#586]
## Requirement 

Identify queries that are not appropriate and send degraded response accordingly 

## Overview 

1. Create a black list of words that needs to be filtered out 
2. Utilize existing services available in Bhashini/Azure (wherever necessary - bot specific) 

## To-do list

- [ ] Create a list of queries that include bad language - (test set) 
- [ ] Run a benchmark on the list of queries that have inappropriate language
- [ ] Create a list of words that need to passed through the check
- [ ] Deploy the services (provided by Bhashini/Azure) that auto-detect and degrade the inappropriate queries 
- [ ] Test the result post integration of filter + services

**Comment by MaunicaKolla815** [comment]
@Amruth-Vamshi & @Gautam-Rajeev - We need to add Azure's profanity services also
